{{ if .Values.hpa.enabled }}
{{ if and (eq .Capabilities.KubeVersion.Major "1") (ge .Capabilities.KubeVersion.Minor "8") }}
apiVersion: autoscaling/v2beta1
{{ else }}
apiVersion: autoscaling/v2alpha1
{{ end }}
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Chart.Name }}-hpa-policy"
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: "{{ .Chart.Name }}-deployment"
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.hpa.metrics.cpu.targetAverageUtilization }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.hpa.metrics.memory.targetAverageUtilization }}
{{ end }}