# The container name used for the run container
container-name-run : "microservices-swift-swift-run"
# The container name used for the tools container
container-name-tools : "microservices-swift-swift-tools"

# The project root on the host for the run container to mount to container-path-run
host-path-run : "."
# The project root on the host for the tools container to mount to container-path-tools
host-path-tools : "."

# The project root in the run container to mount to host-path-run
container-path-run : "/swift-project"
# The project root in the tools container that will be mounted to host-path-tools
container-path-tools : "/swift-project"

# The port mappings between the host and the container in the form [host:container]
container-port-map : "8080:8080"
# The port mappings between the host and the container for the debug port in the form [host:container]
container-port-map-debug : "2048:1024,2049:1025"

# The name for the dockerfile for the run container
dockerfile-run : "Dockerfile"
# The name for the dockerfile for the tools container
dockerfile-tools : "Dockerfile-tools"

# The name of image to create from dockerfile-run
image-name-run : "microservices-swift-swift-run"
# The name of image to create from dockerfile-tools
image-name-tools : "microservices-swift-swift-tools"

# The command to build the code and docker image for RUN
build-cmd-run : "/swift-utils/tools-utils.sh build release"
# The command to execute tests for the code in the tools container
test-cmd : "/swift-utils/tools-utils.sh test"
# The command to build the code and docker image for DEBUG
build-cmd-debug : "/swift-utils/tools-utils.sh build debug"

# The command to run the code in the run container
run-cmd : ""
# The command to execute debug of the code in the tools container
debug-cmd : "/swift-utils/tools-utils.sh debug microservices-swift 1024"
# The command to stop the code
stop-cmd : ""

# The relative path to the helm chart used for Kubernetes deployment
chart-path : "chart/microservices-swift"

# The IBM version of this configuration
version : "0.0.3"